//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerbiSoft.Core.T4EntityFrameworkSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessType
    {
        public AccessType()
        {
            this.AccessPolicyItem = new HashSet<AccessPolicyItem>();
            this.Attendance = new HashSet<Attendance>();
            this.RoundAssignment = new HashSet<RoundAssignment>();
        }
    
        public int ID { get; set; }
        public bool IsDisabled { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedUser { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<bool> IsAssignable { get; set; }
        public int BackColor { get; set; }
        public int ForeColor { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<AccessPolicyItem> AccessPolicyItem { get; set; }
        public virtual ICollection<Attendance> Attendance { get; set; }
        public virtual ICollection<RoundAssignment> RoundAssignment { get; set; }
    }
}
