//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerbiSoft.Core.T4EntityFrameworkSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.Device = new HashSet<Device>();
            this.Employee = new HashSet<Employee>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid CompanyID { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<Device> Device { get; set; }
        public virtual ICollection<Employee> Employee { get; set; }
    }
}
