//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerbiSoft.Core.T4EntityFrameworkSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public Attendance()
        {
            this.TimeTracking = new HashSet<TimeTracking>();
            this.TimeTracking1 = new HashSet<TimeTracking>();
        }
    
        public System.Guid ID { get; set; }
        public bool IsDisabled { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.Guid> EmployeeID { get; set; }
        public System.Guid DeviceID { get; set; }
        public int TypeID { get; set; }
        public string Number { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string Reason { get; set; }
        public bool IsForwarded { get; set; }
        public Nullable<System.DateTime> ForwardedTime { get; set; }
    
        public virtual AccessType AccessType { get; set; }
        public virtual Device Device { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<TimeTracking> TimeTracking { get; set; }
        public virtual ICollection<TimeTracking> TimeTracking1 { get; set; }
    }
}
