//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerbiSoft.Core.T4EntityFrameworkSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public Device()
        {
            this.AddressPolicyAssignment = new HashSet<AddressPolicyAssignment>();
            this.Attendance = new HashSet<Attendance>();
            this.DeviceLog = new HashSet<DeviceLog>();
        }
    
        public System.Guid ID { get; set; }
        public bool IsDisabled { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.Guid> CompanyID { get; set; }
        public Nullable<System.Guid> AreaID { get; set; }
        public int TypeID { get; set; }
        public int StateID { get; set; }
        public int Number { get; set; }
        public string Name { get; set; }
        public string IP { get; set; }
        public int Port { get; set; }
        public int Channel { get; set; }
        public int Interval { get; set; }
        public string SerialNumber { get; set; }
        public string Firmware { get; set; }
        public int Timeout { get; set; }
        public Nullable<System.DateTime> LastSyncDate { get; set; }
        public string LastSyncUser { get; set; }
        public Nullable<int> LastType { get; set; }
    
        public virtual ICollection<AddressPolicyAssignment> AddressPolicyAssignment { get; set; }
        public virtual Area Area { get; set; }
        public virtual ICollection<Attendance> Attendance { get; set; }
        public virtual Company Company { get; set; }
        public virtual DeviceState DeviceState { get; set; }
        public virtual DeviceType DeviceType { get; set; }
        public virtual ICollection<DeviceLog> DeviceLog { get; set; }
    }
}
