//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerbiSoft.Core.T4EntityFrameworkSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Attendance = new HashSet<Attendance>();
            this.CardAssignment = new HashSet<CardAssignment>();
            this.Schedule = new HashSet<Schedule>();
            this.TimeAmountDay = new HashSet<TimeAmountDay>();
            this.TimeExportDetail = new HashSet<TimeExportDetail>();
            this.TimeTracking = new HashSet<TimeTracking>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid CompanyID { get; set; }
        public Nullable<System.Guid> AreaID { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Area Area { get; set; }
        public virtual ICollection<Attendance> Attendance { get; set; }
        public virtual ICollection<CardAssignment> CardAssignment { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<Schedule> Schedule { get; set; }
        public virtual ICollection<TimeAmountDay> TimeAmountDay { get; set; }
        public virtual ICollection<TimeExportDetail> TimeExportDetail { get; set; }
        public virtual ICollection<TimeTracking> TimeTracking { get; set; }
    }
}
