//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerbiSoft.Core.T4EntityFrameworkSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class FunctionalRight
    {
        public FunctionalRight()
        {
            this.RightAssignment = new HashSet<RightAssignment>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedUser { get; set; }
        public int Type { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<RightAssignment> RightAssignment { get; set; }
    }
}
