//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerbiSoft.Core.T4EntityFrameworkSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.AddressAssignment = new HashSet<AddressAssignment>();
            this.RightAssignment = new HashSet<RightAssignment>();
        }
    
        public System.Guid ID { get; set; }
        public bool IsDisabled { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedUser { get; set; }
        public int RealType { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<AddressAssignment> AddressAssignment { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<RightAssignment> RightAssignment { get; set; }
        public virtual User User { get; set; }
    }
}
