//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerbiSoft.Core.T4EntityFrameworkSample
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DpPze_NeuEntities : DbContext
    {
        public DpPze_NeuEntities()
            : base("name=DpPze_NeuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddressAssignment> AddressAssignment { get; set; }
        public virtual DbSet<FunctionalRight> FunctionalRight { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<RightAssignment> RightAssignment { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<RoleAssignment> RoleAssignment { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<AccessPolicy> AccessPolicy { get; set; }
        public virtual DbSet<AccessPolicyItem> AccessPolicyItem { get; set; }
        public virtual DbSet<AccessType> AccessType { get; set; }
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<AddressPolicyAssignment> AddressPolicyAssignment { get; set; }
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<Attendance> Attendance { get; set; }
        public virtual DbSet<BookType> BookType { get; set; }
        public virtual DbSet<BreakAssignment> BreakAssignment { get; set; }
        public virtual DbSet<BreakParameter> BreakParameter { get; set; }
        public virtual DbSet<BreakRule> BreakRule { get; set; }
        public virtual DbSet<CardAssignment> CardAssignment { get; set; }
        public virtual DbSet<CardReader> CardReader { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Device> Device { get; set; }
        public virtual DbSet<DeviceLog> DeviceLog { get; set; }
        public virtual DbSet<DeviceState> DeviceState { get; set; }
        public virtual DbSet<DeviceType> DeviceType { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<IdentityCard> IdentityCard { get; set; }
        public virtual DbSet<Organisation> Organisation { get; set; }
        public virtual DbSet<Reason> Reason { get; set; }
        public virtual DbSet<RoundAssignment> RoundAssignment { get; set; }
        public virtual DbSet<RoundParameter> RoundParameter { get; set; }
        public virtual DbSet<RoundRule> RoundRule { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<ScheduleItem> ScheduleItem { get; set; }
        public virtual DbSet<Setting> Setting { get; set; }
        public virtual DbSet<Task> Task { get; set; }
        public virtual DbSet<TimeAmountDay> TimeAmountDay { get; set; }
        public virtual DbSet<TimeExport> TimeExport { get; set; }
        public virtual DbSet<TimeExportDetail> TimeExportDetail { get; set; }
        public virtual DbSet<TimeItem> TimeItem { get; set; }
        public virtual DbSet<TimeProfile> TimeProfile { get; set; }
        public virtual DbSet<TimeTracking> TimeTracking { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<CustomerAssignment> CustomerAssignment { get; set; }
        public virtual DbSet<ExceptionLog> ExceptionLog { get; set; }
        public virtual DbSet<InformationLog> InformationLog { get; set; }
        public virtual DbSet<Update> Update { get; set; }
        public virtual DbSet<UpdatePackage> UpdatePackage { get; set; }
        public virtual DbSet<User1> User1 { get; set; }
        public virtual DbSet<UserLog> UserLog { get; set; }
    }
}
