//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerbiSoft.Core.T4EntityFrameworkSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organisation
    {
        public Organisation()
        {
            this.Company = new HashSet<Company>();
        }
    
        public System.Guid ID { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<Company> Company { get; set; }
    }
}
