//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerbiSoft.Core.T4EntityFrameworkSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoundAssignment
    {
        public RoundAssignment()
        {
            this.RoundParameter = new HashSet<RoundParameter>();
        }
    
        public System.Guid ID { get; set; }
        public bool IsDisabled { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedUser { get; set; }
        public System.Guid AddressID { get; set; }
        public int TypeID { get; set; }
        public System.Guid RuleID { get; set; }
        public Nullable<System.Guid> ProfileID { get; set; }
        public System.DateTime ValidFrom { get; set; }
    
        public virtual AccessType AccessType { get; set; }
        public virtual Address Address { get; set; }
        public virtual ICollection<RoundParameter> RoundParameter { get; set; }
        public virtual RoundRule RoundRule { get; set; }
        public virtual TimeProfile TimeProfile { get; set; }
    }
}
