//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerbiSoft.Core.T4EntityFrameworkSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTracking
    {
        public TimeTracking()
        {
            this.TimeTracking1 = new HashSet<TimeTracking>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public bool IsDisabled { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedUser { get; set; }
        public System.Guid EmployeeID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.Guid> FromAttendanceID { get; set; }
        public Nullable<System.DateTime> FromTime { get; set; }
        public Nullable<System.Guid> FromReasonID { get; set; }
        public Nullable<System.Guid> ToAttendanceID { get; set; }
        public Nullable<System.DateTime> ToTime { get; set; }
        public Nullable<System.Guid> ToReasonID { get; set; }
        public decimal BreakTime { get; set; }
        public decimal BreakTimeFrom { get; set; }
        public decimal BreakTimeTo { get; set; }
        public decimal WorkTime { get; set; }
        public bool IsControlled { get; set; }
        public Nullable<System.DateTime> ControlledTime { get; set; }
        public bool IsForwarded { get; set; }
        public Nullable<System.DateTime> ForwardedTime { get; set; }
    
        public virtual Attendance Attendance { get; set; }
        public virtual Attendance Attendance1 { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Reason Reason { get; set; }
        public virtual Reason Reason1 { get; set; }
        public virtual ICollection<TimeTracking> TimeTracking1 { get; set; }
        public virtual TimeTracking TimeTracking2 { get; set; }
    }
}
