//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerbiSoft.Core.T4EntityFrameworkSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeProfile
    {
        public TimeProfile()
        {
            this.AccessPolicyItem = new HashSet<AccessPolicyItem>();
            this.BreakAssignment = new HashSet<BreakAssignment>();
            this.RoundAssignment = new HashSet<RoundAssignment>();
            this.TimeItem = new HashSet<TimeItem>();
        }
    
        public System.Guid ID { get; set; }
        public bool IsDisabled { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedUser { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<AccessPolicyItem> AccessPolicyItem { get; set; }
        public virtual ICollection<BreakAssignment> BreakAssignment { get; set; }
        public virtual ICollection<RoundAssignment> RoundAssignment { get; set; }
        public virtual ICollection<TimeItem> TimeItem { get; set; }
    }
}
