//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerbiSoft.Core.T4EntityFrameworkSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class User1
    {
        public User1()
        {
            this.CustomerAssignment = new HashSet<CustomerAssignment>();
            this.UserLog = new HashSet<UserLog>();
        }
    
        public System.Guid ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool ChangePassword { get; set; }
        public string Phone { get; set; }
        public string Mail { get; set; }
        public bool IsValidated { get; set; }
        public bool IsOnlyLiveView { get; set; }
    
        public virtual ICollection<CustomerAssignment> CustomerAssignment { get; set; }
        public virtual ICollection<UserLog> UserLog { get; set; }
    }
}
